version: "3.8"

networks:
  chat:
    driver: bridge

services:
  auth-service:
    image: "auth-service"
    build: "./auth-service"
    container_name: "auth"
    ports:
      - 8080:8080
      - 8001:8001
    restart: always
    command: "bash ./wait-for-it.sh -t 0 db:5432 -- bash start.sh"
    env_file:
      - ./docker-conf/auth-service/env.yml
    environment:
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
    networks:
      - chat

  chat-service:
    image: "chat-service"
    build: "./chat-service"
    container_name: "chat"
    ports:
      - 8080:8080
      - 8002:8002
    restart: always
    command: "bash ./wait-for-it.sh -t 0 chat-db:5432 -- bash start.sh"
    deploy:
      mode: replicated
      replicas: 2
    env_file:
      - ./docker-conf/chat-service/env.yml
    environment:
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8002
    networks:
      - chat